In [ ]:
import numpy as np 
import random
import matplotlib.pyplot as plt
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D,Dense,Flatten,Dropout
from tensorflow.keras.preprocessing.image import ImageDataGenerator

In [29]:
X_train=np.loadtxt('input.csv',delimiter=',')
Y_train=np.loadtxt('labels.csv',delimiter=',')

X_test=np.loadtxt('input_test.csv',delimiter=',')
Y_test=np.loadtxt('labels_test.csv',delimiter=',')

In [30]:
X_train=X_train.reshape(len(X_train),100,100,3)
Y_train=Y_train.reshape(len(Y_train),1)

X_test=X_test.reshape(len(X_test),100,100,3)
Y_test=Y_test.reshape(len(Y_test),1)

X_train=X_train/255.0
X_test=X_test/255.0

datagen = ImageDataGenerator(
rotation_range=20,
width_shift_range=0.2,
height_shift_range=0.2,
horizontal_flip=True,
zoom_range=0.2
)

In [31]:
print("Shape of X_train:",X_train)
print("Shape of Y_train:",Y_train)
print("Shape of X_test:",X_test)
print("Shape of Y_test:",Y_test)

Shape of X_train: [[[[0.14509804 0.15294118 0.09803922]
   [0.10196078 0.09411765 0.03529412]
   [0.13333333 0.09803922 0.03921569]
   ...
   [0.22352941 0.17254902 0.1372549 ]
   [0.23921569 0.18431373 0.14901961]
   [0.25490196 0.2        0.16470588]]

  [[0.17647059 0.16862745 0.10980392]
   [0.10980392 0.09803922 0.03137255]
   [0.20392157 0.15686275 0.09411765]
   ...
   [0.21176471 0.16078431 0.1254902 ]
   [0.22352941 0.16862745 0.13333333]
   [0.23921569 0.18431373 0.14901961]]

  [[0.20392157 0.17647059 0.10196078]
   [0.1254902  0.09411765 0.01960784]
   [0.27058824 0.21176471 0.1372549 ]
   ...
   [0.21176471 0.15686275 0.11372549]
   [0.21960784 0.16470588 0.12156863]
   [0.23137255 0.17647059 0.13333333]]

  ...

  [[0.07843137 0.15294118 0.        ]
   [0.39607843 0.49019608 0.2627451 ]
   [0.59607843 0.71372549 0.47058824]
   ...
   [0.18039216 0.16078431 0.0745098 ]
   [0.23529412 0.21568627 0.12941176]
   [0.23529412 0.21568627 0.12941176]]

  [[0.18039216 0.25490196 0

In [37]:
idx=random.randint(0,len(X_train))
plt.imshow(X_train[idx,:])
plt.show()

NameError: name 'plt' is not defined

In [ ]:
model=Sequential([
  Conv2D(32,(3,3),activation='relu',input_shape=(100,100,3)),
  MaxPooling2D((2,2)),

  Conv2D(32,(3,3),activation='relu'),
  MaxPooling2D((2,2)),

  Flatten(),
  Dense(64,activation='relu'),
  Dense(1,activation='sigmoid')
])

In [ ]:
model=Sequential()

model.add(Conv2D(32, (3,3), activation='relu', input_shape=(100,100,3)))
model.add(MaxPooling((2,2)))
model.add(Dropout(0.25))

model.add(Conv2D(64,(3,3),activation='relu'))
model.add(MaxPooling2D((2,2)))
model.add(Dropout(0.25))

model.add(Conv2D(128,(3,3),activation='relu'))
model.add(MaxPooling2D((2,2)))
model.add(Dropout(0.25))

model.add(Flatten())
model.add(Dense(120,activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(1,activation=sigmoid))


In [ ]:
model.compile(loss='binary_crossentrophy',optimizer='adam',metric=['accuracy'])

In [ ]:
model.fit(datagen.flow(X_train,Y_train,batch_size=32),
      epochs=30,
      validation_data(X_test,Y_test),
      verbose=1)


In [ ]:
idx2=random.randint(0,len(Y_test))
plt.imshow(X_test[idx2,:])
plt.show()

y_pred=model.predict(X_test[idx2,:].reshape(1,100,100,3))
y_pred=y_pred>0.5

if(y_pred==0):
  pred='dog'
else:
  pred='cat'

print("Our model says it is a:",pred)

In [ ]:
model.save('model.h5')
print('saved model to model.h5')